// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo5KDawDDs_58GUh-Yi2J_b0Vls69jvJ0',
    appId: '1:600583171467:web:022012244db39e15cf138e',
    messagingSenderId: '600583171467',
    projectId: 'doit-5b02a',
    authDomain: 'doit-5b02a.firebaseapp.com',
    storageBucket: 'doit-5b02a.appspot.com',
    measurementId: 'G-VGJ7G0B2JF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaFM8nftAWdhUxJHYZvXCJd6-3Wo5zZuI',
    appId: '1:600583171467:android:7e02d3206a97d7a5cf138e',
    messagingSenderId: '600583171467',
    projectId: 'doit-5b02a',
    storageBucket: 'doit-5b02a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCu7KfR56MJ5ZPhaXwfJ7GyrgZkVQ5B2vo',
    appId: '1:600583171467:ios:e056d95ac94313b3cf138e',
    messagingSenderId: '600583171467',
    projectId: 'doit-5b02a',
    storageBucket: 'doit-5b02a.appspot.com',
    iosClientId: '600583171467-fvbnskqhuv4ap7jnjrmng91gai36mt8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.doit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCu7KfR56MJ5ZPhaXwfJ7GyrgZkVQ5B2vo',
    appId: '1:600583171467:ios:e056d95ac94313b3cf138e',
    messagingSenderId: '600583171467',
    projectId: 'doit-5b02a',
    storageBucket: 'doit-5b02a.appspot.com',
    iosClientId: '600583171467-fvbnskqhuv4ap7jnjrmng91gai36mt8v.apps.googleusercontent.com',
    iosBundleId: 'com.example.doit',
  );
}
